In [2]:
import pandas as pd

In [3]:
dados = pd.read_csv("data/Customer-Churn.csv")

In [4]:
dados.shape

(7043, 18)

In [5]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [6]:
# modificacao de forma manual
traducao_dict = {
    "Sim" : 1,
    "Nao" : 0
}

dados_modificados = dados[["Conjuge", "Dependentes", "TelefoneFixo", "PagamentoOnline", "Churn"]].replace(traducao_dict)
dados_modificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [7]:
# modificacao pelo get_dummies
dummy_dados = pd.get_dummies(dados.drop(["Conjuge", "Dependentes", "TelefoneFixo", "PagamentoOnline", "Churn"], axis=1))

# juncao dos dados transformados com os que ja tinhamos
dados_final = pd.concat([dados_modificados, dummy_dados], axis=1)
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [8]:
dados_final.shape

(7043, 39)

---
# Para saber mais: divisão dos dados em treino e teste

Separar o conjunto de dados em **treino** e **teste** é uma parte imortante para conseguirmos medir o desempenho real de um modelo de machine learning. Essa etapa consiste em dedicar parte do conjunto de dados para treinar o modelo e uma outra parte para teste. Mas qual o motivo de fazer isso?

Imagine que você vai fazer uma prova e o(a) professor(a) passa uma atividade de revisão antes para treinar em casa. Chegando na prova, você percebe que as questões são exatamente iguais à revisão passada pelo(a) professor(a). Como você já sabia as questões, tirou 10! Isso é exatamente o que acontece quando utilizamos os mesmos dados para treinar e testar.

Como os dados são conhecidos pelo modelo, ele simplesmente vai acertar tudo (ou quase tudo) na etapa de teste, pois são os mesmos dados. Para resolver isso, dividimos o conjunto de dados em treino e teste, sendo esse último para simular dados nunca antes vistos pelo modelo.

## Dados de treino

Os dados de treino são aqueles utilizados para a criação e treinamento do modelo. Normalmente a maioria dos dados, cerca de 70%, são utilizados para treinamento.

## Dados de teste

Os dados de teste são utilizados para comprovar que o modelo realmente funciona. Eles não são utilizados no treinamento do modelo e normalmente representam 30% da totalidade dos dados.

Além disso, no momento de reailzar a separação desses dados é importante que ela seja feita de forma aleatória, para garantirmos que não haverá nenhum padrão no momento de divisão dos dados. Assim, cada amostra terá a mesma probabilidade de ser selecionada.

---

# KNN por trás dos panos

In [9]:
xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [10]:
#Ymaria = ?

In [11]:
# Divisão em inputs e outputs
x = dados_final.drop("Churn", axis=1)
y = dados_final["Churn"]

In [12]:
# Biblioteca para padronizar os dados
from sklearn.preprocessing import StandardScaler

In [13]:
norm = StandardScaler()
x_normalizado = norm.fit_transform(x)
x_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [14]:
x_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [15]:
xmaria_normalizado = norm.transform(pd.DataFrame(xmaria, columns=x.columns))
xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

---
## Distância Euclidiana:
$$\LARGE\sqrt{\sum_{i=1}^k (a_i - b_i)^2}$$

---

In [16]:
import numpy as np

In [17]:
a = xmaria_normalizado
type(a)

numpy.ndarray

In [18]:
b = x_normalizado[0]
type(b)

numpy.ndarray

In [19]:
# 1 - começamos subtraindo
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [20]:
# 2 - depois realizamos a exponenciação
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 6.04585093e+00, 0.00000000e+00, 4.48357062e+00,
        0.00000000e+00, 5.84230682e+00]])

In [21]:
# 3 - a soma
np.sum(np.square(a-b))

84.07574038273466

In [22]:
# 4 - então tiramos a raiz e temos nossa distância
np.sqrt(np.sum(np.square(a-b)))

9.169282435541762

---
# Para saber mais: funções de distância

No algoritmo KNN, para que seja feita a classificação dos registros com base nos vizinhos mais próximos, é necessário utilizar alguma medida para identificar o quão próximo o registro está dos seus vizinhos. Existem diversas medidas para se avaliar essa proximidade entre variáveis numéricas que recebem o nome de medidas de distância. Quanto maios o valor dessa medida, mais distante um elemento está do outro, ou seja, menor a similaridade entre eles.

Considere a tabela a seguir com duas observações e n variáveis para o entendimento das medidas de distância.

| Observação | Variável 1 | Variável 2 | ... | Variável n |
| --- | --- | --- | --- | --- |
| X | X1 | X2 | ... | Xn |
| Y | Y1 | Y2 | ... | Yn |

* ### Distância Euclidiana

A medida de distância mais conhecida e usada é a **distância euclidiana**. Ela consiste em subtrair as coordenadas de uma observação pela outra observação, elevar ao quadrado os resultados, somar todos os valores e extrair a raiz quadrada.

$$\Large d = \sqrt{(X_1 - Y_1)^2 + ... + (X_n - Y_n)^2}$$

* ### Distância de Manhattan

Uma distância que considera apenas a soma dos módulos das diferenças entre cada par de coordenadas.

$$\Large d = |X_1 - Y_1| + ... + |X_n - Y_n|$$

* ### Distância de Minkowski

Uma medida de distância que é a generalização de outras distâncias, como a distância euclidiana e a de Manhattan. Consiste em extrair o módulo da diferença entre cada par de coordenadas elevando o resultado a m, realizar a soma de todos os termos e, por fim, tirar a raiz m-ésima, em que m é um número qualquer. A distância euclidiana é um caso à parte quando m é igual a 2 e a distância de Manhattan é um caso à parte quando m é igual a 1.

$$\Large d = \sqrt[m]{|X_1 - Y_1|^m + ... + |X_n - Y_n|^m}$$

* ### Distância de Chebyshev

É uma medida de distância que considera apenas o valor máximo entre os módulos das diferenças entre as variáveis. Dessa forma, leva em consideração apenas a variável que possui a maior diferença de valores entre as duas observações.

$$\Large d = máx{|X_1 - Y_1|, ..., |X_n - Y_n|}$$

Existem diversas outras medidas de distância que podem ser calculadas e cada uma delas impacta diretamente no resultado do modelo. As distâncias apresentadas aqui podem ser utilizadas no algoritmo KNN do scikit-learn, sendo a distância de Minkowski a medida de distância padrão ao instanciar o algoritmo, como pode ser checado na [documentação](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html).

Podemos modificar a medida de distância utilizando o argumento `metric` da função `sklearn.neighbors.KNeighborsClassifier`. Com base nas medidas que foram apresentadas no texto, o parâmetro pode receber os seguintes valores:

    * "euclidean" para a distância euclidiana;
    * "manhattan" para a distância de Manhattan;
    * "minkowski" para a distância de Minkowski;
    * "chebyshev" para a distância de Chebyshev.

Caso tenha interesse em descobrir o funcionamento ou outras medidas de distância que podem ser utilizadas, confira a documentação do [sklearn.metrics.DistanceMetric](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html#sklearn.metrics.DistanceMetric).

---

### Implementando o modelo

In [23]:
# Biblioteca para divisão dos dados
from sklearn.model_selection import train_test_split

In [24]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x_normalizado, y,
                                                        test_size=0.3, random_state=123)

### Treino e teste  

In [25]:
# Biblioteca para criarmos o mmodelo de machine learning
from sklearn.neighbors import KNeighborsClassifier

In [26]:
# Instanciar o modelo (criamos o modelo) - por padrão são 5 vizinhos
knn = KNeighborsClassifier(metric="euclidean")

In [27]:
# Treinando o modelo com os dados de treino
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [28]:
# Testando o modelo com os dados de teste
predito_knn = knn.predict(x_teste)
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

## KNN mão na massa

In [29]:
import numpy as np

def calcula_distancia(dados_clientes, dados_maria, numero_clientes):
    distancias = []

    # loop para percorrer cliente por cliente
    for i in range(numero_clientes):
        dist1 = dados_maria - dados_clientes[i] # subtração dos atributos
        soma_quadrado = np.sum(np.square(dist1)) # exponenciação e soma dos atributos
        distancias.append(np.sqrt(soma_quadrado)) # raiz quadrada da soma anterior

    return distancias

calcula_distancia(x_normalizado, xmaria_normalizado, 10)

[9.169282435541762,
 8.742314068192332,
 7.96104771727276,
 9.683687116435184,
 7.35756725091328,
 8.58650261645753,
 8.411628863624525,
 10.145869884558158,
 8.97159048640628,
 7.5587041367106105]

---
### Fórmula do teorema de Naïve Bayes:

$$\Large P(y|X) = \dfrac{P(X|y) * P(y)}{P(X)}$$

---
### Multivariada de Bernoulli:

$$\Large P(x_i|y) = P(i|y)x_i + (1 - P(i|y))(1 - x_i)$$

#### Os dados estão em variáveis binárias.
---

### Para saber mais: probabilidade condicional e Bayes

O teorema de Bayes é uma fórmula utilizada para calcular a probabilidade de um evento ocorrer sabendo que um outro evento, chamado de condicionante, já ocorreu, denominado **probabilidade condicional**. Sua notação é dada por P(A|B), que significa a probabilidade de A dado que B já aconteceu e é definido pela seguinte equação:

$$\Large P(A|B) = \dfrac{P(B|A) * P(A)}{P(B)}$$

Onde:

    * P(B|A): probabilidade de B acontecer dado que A já aconteceu;
    * P(A): probabilidade de A acontecer;
    * P(B): probabilidade de B acontecer.

Falando dessa forma, pode ficar complicado de visualizar na prática o que isso realmente significa. Como o teorema de Bayes envolve probabilidade, pode ser aplicado a inúmeros contextos. Vamos utilizar aqui um exemplo envolvendo a área da saúde, mas o teorema poderia ser utilizado em outras áreas. Considere o exemplo:

| | Covid-19 (5%) | Sem Covid-19 (95%) |
| --- | --- | --- |
| Teste positivo | 85% | 10% |
| Teste negativo | 15% | 90% |

Primeiramente, vamos entender o que está na tabela. Sabemos, através de pesquisas realizadas anteriormente, que há uma probabilidade de 5% de ter Covid-19. Consequentemente, há uma probabilidade de 95% de não ter. Quem tem a doença está na coluna "Covid-19 (5%)" e possui uma probabilidade de 85% de testar positivo e 15% de negativo. Já quem não tem está na coluna "Sem Covid-19 (95%)" e possui uma possibilidade de 10% de testar positivo e 90% de negativo.

De posse dessas informações, vamos repsonder à pergunta:
quais as chances de ter Covid-19 dado que o teste deu positivo?

    * Evento A: ter Covid-19
    * Evento B positivo no teste (evento condicionante)

Utilizando a fórmula apresentada anteriormente, precisamos definir algumas probabilidades, como:

    * P(B|A): probabilidade do teste ser positivo dado que a pessoa tem Covid-19, que é de 85% ou 0.85, de acordo com a tabela.
    * P(A): probabilidade de ter Covid-19. Observando a tabela, temos que é de 5%, ou 0.05.
    * P(B): a probabilidade do teste ser positivo.

A P(B) não conseguimos encontrar diretamente na tabela, pois a probabilidade do teste ser positivo pode acontecer quando a pessoa testada possui a doença ou não (chamado também de complementar). Logo, a probabilidade P(B) pode ser calculada como:

$$\Large P(B) = P(B|A) * P(A) + P(B|A^c) * P(A^c)$$

    * P(B|AC): probabilidade do teste ser positivo dado que a pessoa não possui Covid-19, que é 10% ou 0.1.
    * P(AC): probabilidade da pessoa não ter Covid-19, que é 95% ou 0.95.

Novamente, as informções acima foram retiradas diretamente da tabela. Pronto, agora temos todas as informações que precisamos. Colocando na equação temos que:

$$\Large P(A|B) = \dfrac{P(B|A) * P(A)}{P(B)} = \dfrac{0.85 * 0.05}{0.1375} = 0.31$$

Logo, as chances de ter Covid-19, dado que o teste deu positivo, são de 31%.

---

# Treinamento e teste

In [30]:
x_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [31]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [32]:
# Escolho utilizar mediana, porque é o valor central dos nossos dados ordenados
np.median(x_treino)

-0.5259273725834717

In [33]:
# Biblioteca para criamos o modelo de machine learning
from sklearn.naive_bayes import BernoulliNB

In [34]:
# Criamos o modelo
bnb = BernoulliNB(binarize=-0.5259273)

In [35]:
bnb.fit(x_treino, y_treino)

BernoulliNB(binarize=-0.5259273)

In [36]:
predito_bnb = bnb.predict(x_teste)
predito_bnb

array([1, 0, 0, ..., 0, 1, 0])